name: JSON Env from Repo

on:
  workflow_dispatch:

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Show JSON
        run: |
          echo '${{ vars.JSON_DATA }}' > payload.json
          cat payload.json

      - name: Loop through JSON values
        run: |
          echo "$JSON_DATA" | jq -c '.[]' | while read item; do
            name=$(echo "$item" | jq -r '.Name')
            value=$(echo "$item" | jq -r '.value')
            
            echo "Processing Name=$name, Value=$value"

            # Example command using values
            echo "Running task with $name and $value"
          done
