name: JSON Env from Repo

on:
  workflow_dispatch:

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Parse JSON payload from GitHub Environment
        id: parse
        run: |
          echo '${{ vars.MY_JSON }}' > payload.json
          cat payload.json
